/*
 * Vulture - Win32 libpurple client
 *
 * resource.h: Resource definitions for Vulture. Originally generated by
 * ResEdit.
 *
 * Copyright (C) 2009, Gregor Dick <gdick@soc.pidgin.im>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02111-1301  USA
 */


#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDC_BTN_ACCOUNT_ADD		1001
#define IDC_BTN_ACCOUNT_DELETE		1002
#define IDC_BTN_ACCOUNT_PROPERTIES	1003
#define IDC_BUDDY_ICON			1004
#define IDC_CBEX_ACCOUNTS		1005
#define IDC_CBEX_STATUS			1006
#define IDC_EDIT_STATUSMSG		1007
#define IDC_LIST_ACCOUNTS		1008
#define IDC_RICHEDIT_CONV		1009
#define IDC_RICHEDIT_INPUT		1010
#define IDC_STATIC_DETAILS		1011
#define IDC_STATIC_ICON			1012
#define IDC_STATIC_NAME			1013
#define IDC_STATIC_STATUS		1014
#define IDC_STATIC_TOPIC		1015
#define IDC_TAB_CONVERSATIONS		1016
#define IDC_TREE_BLIST			1017
#define IDC_TREE_NAMES			1018
#define IDC_EDIT_USERNAME		1019
#define IDC_EDIT_ALIAS			1020
#define IDC_CBEX_GROUP			1021
#define IDC_EDIT_STRING			1022


#define IDD_ACCOUNTS			101
#define IDD_BLIST			102
#define IDD_CHAT			103
#define IDD_CONVCONT			104
#define IDD_IM				105
#define IDD_JOINCHAT			106
#define IDD_STATUS			107
#define IDD_ADDBUDDY			108
#define IDD_IMBUDDY			109
#define IDD_ADDCHAT			110
#define IDD_ADDGROUP			111


#define IDM_BLIST			1001
#define IDM_BLIST_ACCOUNTS_MANAGE	40001
#define IDM_BLIST_BUDDIES_CLOSE		40000
#define IDM_BLIST_BUDDIES_JOINCHAT	40002
#define IDM_BLIST_BUDDIES_ADDBUDDY	40003
#define IDM_BLIST_VIEW_SHOWOFFLINE	40004
#define IDM_BLIST_BUDDIES_IM		40005
#define IDM_BLIST_BUDDIES_ADDCHAT	40006
#define IDM_BLIST_BUDDIES_ADDGROUP	40007
#define IDM_BLIST_VIEW_SHOWEMPTYGROUPS	40008

#define IDM_BLIST_CONTEXT		1002
#define IDM_BLIST_CONTEXT_ACTIVATE	40201
#define IDM_BLIST_CONTEXT_GETINFO	40202
#define IDM_BLIST_CONTEXT_SENDFILE	40203
#define IDM_BLIST_CONTEXT_ADDPOUNCE    	40204
#define IDM_BLIST_CONTEXT_VIEWLOG	40205
#define IDM_BLIST_CONTEXT_SHOWOFFLINE	40206
#define IDM_BLIST_CONTEXT_ALIAS		40207
#define IDM_BLIST_CONTEXT_REMOVE	40208
#define IDM_BLIST_CONTEXT_BLOCK		40209
#define IDM_BLIST_CONTEXT_CUSTOMICON	40210
#define IDM_BLIST_CONTEXT_REMOVEICON	40211
#define IDM_BLIST_CONTEXT_EXPAND	40212
#define IDM_BLIST_CONTEXT_AUTOJOIN	40213
#define IDM_BLIST_CONTEXT_PROPERTIES	40214
#define IDM_BLIST_CONTEXT_COLLAPSE	40215
#define IDM_BLIST_CONTEXT_ADDBUDDY      40216
#define IDM_BLIST_CONTEXT_ADDCHAT       40217
#define IDM_BLIST_CONTEXT_ADDGROUP      40218

#define IDM_CONV			1003
#define IDM_CONV_CONV_CLOSE		40401

#define IDM_BUDDYICON_CONTEXT           1004
#define IDM_BUDDYICON_CONTEXT_SET       40601
#define IDM_BUDDYICON_CONTEXT_REMOVE    40602

/* For dynamic menu items not sent as WM_COMMAND notifications. */
#define IDM_DYNAMIC_FIRST		50000


#define IDR_ACCEL_MAIN			2001


#define IDB_STATUS_ICONS		3001


#define IDS_ERROR_BLIST			1
#define IDS_ERROR_PURPLEINIT		2
#define IDS_ACCMGR_ACCOUNT		3
#define IDS_ACCMGR_PROTOCOL		4
#define IDS_ERROR_CONVCONTCLASS		5
#define IDS_ERROR_RICHEDIT		6
#define IDS_QUERY_DELGROUP		7
#define IDS_QUERY_DELCONTACT		8
#define IDS_BUDDYICON_FILTER		9
#define IDS_BUDDYICON_TITLE		10
#define IDS_OFFLINE			11
