<div id="footer">
<a href="http://www.dvlabs.com"><img src="/shared/img/button.dvlabs.jpg" alt="Hosted by DVLABS" /></a>
<a href="http://blendinteractive.com"><img src="/shared/img/button.blend.png" alt="Design by Blend Interactive" /></a>
<a href="http://sourceforge.net"><img src="http://sourceforge.net/sflogo.php?group_id=235&amp;type=1" width="88" height="31" alt="SourceForge.net" /></a>
</div>

</body>
</html>

