<div id="footer">
<a href="http://www.networkredux.com/"><img src="/shared/img/button.networkredux.jpg" alt="Hosted by NetworkRedux" title="Hosted by NetworkRedux" /></a>
<a href="http://blendinteractive.com/"><img src="/shared/img/button.blend.png" alt="Design by Blend Interactive" title="Design by Blend Interactive" /></a>
<a href="http://sourceforge.net/"><img src="http://sourceforge.net/sflogo.php?group_id=235&amp;type=1" width="88" height="31" alt="SourceForge.net" /></a>
</div>

<!-- Begin Google Analytics tracking code -->
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-2814037-1");
pageTracker._setDomainName(".pidgin.im");
pageTracker._trackPageview();

var secondTracker = _gat._getTracker("UA-6596609-1");
secondTracker._initData();
secondTracker._trackPageview("/1527532502/test");
</script>
<!-- End Google Analytics tracking code -->

</body>
</html>

