
<link href="/shared/multibox/multibox.css" rel="stylesheet" type="text/css" />
<!--[if lte IE 6]><link rel="stylesheet" href="/shared/multibox/ie6.css" type="text/css" media="all" /><![endif]-->

<script type="text/javascript" src="/shared/multibox/mootools.js"></script>
<script type="text/javascript" src="/shared/multibox/multibox.js"></script>

<script type="text/javascript">
window.addEvent('load', function() {
  new MultiBox('multibox', {
      descClassName:'multiboxD',
      openFromLink:false
  });
});
</script>

